spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

com.gaggle.assessment.musicinfo:
  webhook:
    url: "https://webhook.site/78a6f62c-1aba-4368-8da8-47250718403b"